/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectrental;

/**
 *
 * @author Axioo
 */
public class CarCardGUI extends javax.swing.JPanel {
    
    public void setData(String brand, String transmission, double price, String plate, String statusMobil, String imagePath) {
    merk.setText(brand);
    detail.setText(transmission + " | " + plate);
    
    java.text.NumberFormat nf = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
    harga.setText(nf.format(price).replace(",00", "") + " / Hari");
    
    status.setText("  " + statusMobil.toUpperCase() + "  ");
    if (statusMobil.equalsIgnoreCase("Available")) {
        status.setBackground(new java.awt.Color(220, 245, 220));
        status.setForeground(new java.awt.Color(39, 174, 96));   
    } else {
        status.setBackground(new java.awt.Color(253, 235, 235)); 
        status.setForeground(new java.awt.Color(192, 57, 43));  
    }
   
    boolean imageLoaded = false;
    if (imagePath != null && !imagePath.trim().isEmpty()) {
        try {
            String fullPath = "../rental-mobil/storage/app/public/" + imagePath;
            java.io.File file = new java.io.File(fullPath);
            System.out.println("[DEBUG] Image path: " + file.getAbsolutePath() + " | exists: " + file.exists());
            if (file.exists()) {
                java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(file);
                if (img != null) {
                    java.awt.Image scaledImg = img.getScaledInstance(160, 100, java.awt.Image.SCALE_SMOOTH);
                    Gambar.setIcon(new javax.swing.ImageIcon(scaledImg));
                    Gambar.setText("");
                    Gambar.setBorder(null);
                    imageLoaded = true;
                } else {
                    // ImageIO returned null - try loading via ImageIcon directly as fallback
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(file.getAbsolutePath());
                    if (icon.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE || icon.getIconWidth() > 0) {
                        java.awt.Image scaledImg = icon.getImage().getScaledInstance(160, 100, java.awt.Image.SCALE_SMOOTH);
                        Gambar.setIcon(new javax.swing.ImageIcon(scaledImg));
                        Gambar.setText("");
                        Gambar.setBorder(null);
                        imageLoaded = true;
                    } else {
                        System.out.println("[WARN] ImageIO.read returned null and ImageIcon fallback also failed for: " + fullPath);
                    }
                }
            } else {
                System.out.println("[WARN] File not found: " + file.getAbsolutePath());
            }
        } catch (Exception ex) {
            System.out.println("[ERROR] Failed to load image: " + ex.getMessage());
            ex.printStackTrace();
        }
    }
    
    if (!imageLoaded) {
        Gambar.setIcon(null);
        Gambar.setText("No Photo");
        Gambar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        Gambar.setForeground(new java.awt.Color(150, 150, 150));
        Gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
    }
}
    
    /**
     * Creates new form CarCardGUI
     */
    public CarCardGUI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        Gambar = new javax.swing.JLabel();
        merk = new javax.swing.JLabel();
        detail = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        setPreferredSize(new java.awt.Dimension(180, 250));
        setLayout(new java.awt.BorderLayout(5, 5));

        Gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gambar.setPreferredSize(new java.awt.Dimension(160, 100));
        add(Gambar, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel contentPanel = new javax.swing.JPanel();
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));

        merk.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)); // NOI18N
        merk.setForeground(new java.awt.Color(44, 62, 80));
        merk.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        contentPanel.add(merk);
        contentPanel.add(javax.swing.Box.createVerticalStrut(2));

        detail.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11)); // NOI18N
        detail.setForeground(new java.awt.Color(127, 140, 141));
        detail.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        contentPanel.add(detail);
        contentPanel.add(javax.swing.Box.createVerticalStrut(5));

        status.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10)); // NOI18N
        status.setOpaque(true);
        status.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        contentPanel.add(status);
        contentPanel.add(javax.swing.Box.createVerticalStrut(5));

        harga.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13)); // NOI18N
        harga.setForeground(new java.awt.Color(41, 128, 185));
        harga.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        contentPanel.add(harga);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel merk;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
